export const S = {
  root:       { minHeight:"100vh", background:"#020c1b", display:"flex", justifyContent:"center", alignItems:"flex-start", fontFamily:"'DM Sans','Segoe UI',sans-serif", padding:"0 0 40px" },
  app:        { width:"100%", maxWidth:420, background:"#0d1f35", minHeight:"100vh", display:"flex", flexDirection:"column", color:"#e2e8f0" },
  header:     { display:"flex", justifyContent:"space-between", alignItems:"center", padding:"12px 14px", background:"#061120", borderBottom:"1px solid #1e3a5f", gap:6, flexWrap:"wrap" },
  logo:       { fontWeight:800, fontSize:17, letterSpacing:"-0.5px", color:"#f0c040" },
  navBtns:    { display:"flex", gap:5, alignItems:"center", flexWrap:"wrap" },
  navBtn:     { background:"#1e3a5f", border:"none", color:"#94a3b8", borderRadius:8, padding:"6px 10px", cursor:"pointer", fontSize:13, fontWeight:600 },
  screen:     { padding:"16px", flex:1, display:"flex", flexDirection:"column", gap:12 },
  title:      { margin:0, fontSize:20, fontWeight:800, color:"#f1f5f9", letterSpacing:"-0.5px" },
  settingBox: { background:"#061120", borderRadius:14, padding:"14px 16px", border:"1px solid #1e3a5f", display:"flex", flexDirection:"column", gap:8 },
  settingLabel:    { fontSize:11, fontWeight:800, color:"#64748b", letterSpacing:1, textTransform:"uppercase" },
  settingControls: { display:"flex", gap:6, flexWrap:"wrap" },
  settingBtn:      { border:"none", borderRadius:8, padding:"6px 12px", fontWeight:700, fontSize:13, cursor:"pointer" },
  settingHint:     { fontSize:12, color:"#334155" },
  playerList: { display:"flex", flexDirection:"column", gap:7 },
  playerChip: { display:"flex", alignItems:"center", gap:10, background:"#122236", borderRadius:12, padding:"10px 14px", border:"1px solid #1e3a5f" },
  avatar:     { width:32, height:32, borderRadius:"50%", background:"linear-gradient(135deg,#1d4ed8,#7c3aed)", display:"flex", alignItems:"center", justifyContent:"center", fontWeight:700, fontSize:14, color:"#fff", flexShrink:0 },
  avatarSm:   { width:22, height:22, borderRadius:"50%", background:"linear-gradient(135deg,#1d4ed8,#7c3aed)", display:"inline-flex", alignItems:"center", justifyContent:"center", fontWeight:700, fontSize:10, color:"#fff", marginRight:6, flexShrink:0 },
  avatarXs:   { width:16, height:16, borderRadius:"50%", background:"linear-gradient(135deg,#1d4ed8,#7c3aed)", display:"inline-flex", alignItems:"center", justifyContent:"center", fontWeight:700, fontSize:8, color:"#fff", marginRight:4, flexShrink:0 },
  playerName: { flex:1, fontWeight:600, fontSize:15 },
  removeBtn:  { background:"none", border:"none", color:"#475569", cursor:"pointer", fontSize:13, padding:"2px 4px" },
  addRow:     { display:"flex", gap:8 },
  input:      { flex:1, background:"#122236", border:"1px solid #1e3a5f", borderRadius:10, padding:"10px 14px", color:"#e2e8f0", fontSize:14, outline:"none" },
  addBtn:     { background:"#1d4ed8", border:"none", color:"#fff", borderRadius:10, width:42, fontSize:20, cursor:"pointer", fontWeight:700 },
  bigBtn:     { background:"linear-gradient(135deg,#1d4ed8,#7c3aed)", border:"none", color:"#fff", borderRadius:12, padding:"14px", fontWeight:800, fontSize:16, cursor:"pointer" },
  ghostBtn:   { background:"#122236", border:"1px solid #1e3a5f", color:"#94a3b8", borderRadius:12, padding:"14px 16px", fontWeight:700, fontSize:14, cursor:"pointer" },
  rowBtns:    { display:"flex", gap:10, alignItems:"stretch" },
  shuffleBtn: { display:"flex", alignItems:"center", gap:12, border:"2px solid", borderRadius:14, padding:"14px 16px", cursor:"pointer", color:"#86efac", transition:"all 0.3s", textAlign:"left" },
  teamsRow:   { display:"flex", gap:10, alignItems:"flex-start" },
  teamBox:    { flex:1, background:"#0a192e", borderRadius:14, padding:12, border:"2px solid #1e3a5f", cursor:"pointer", transition:"border-color 0.2s", minHeight:80 },
  teamLabel:  { fontWeight:800, fontSize:11, color:"#64748b", marginBottom:6, letterSpacing:1, textTransform:"uppercase" },
  teamPlayer: { display:"flex", alignItems:"center", fontWeight:600, fontSize:13, marginBottom:3 },
  emptySlot:  { color:"#334155", fontSize:12, fontStyle:"italic", marginTop:4 },
  vsSmall:    { paddingTop:32, color:"#334155", fontWeight:900, fontSize:14 },
  benchSection:{ background:"#0a192e", borderRadius:12, padding:12, border:"1px solid #1e3a5f" },
  benchLabel: { fontWeight:800, fontSize:11, color:"#64748b", letterSpacing:1, textTransform:"uppercase", marginBottom:8 },
  benchRow:   { display:"flex", flexWrap:"wrap", gap:7 },
  benchChip:  { display:"flex", alignItems:"center", background:"#122236", border:"1px solid #1e3a5f", borderRadius:20, padding:"5px 10px", color:"#cbd5e1", fontWeight:600, fontSize:12, cursor:"pointer" },
  winnerBanner:{ background:"linear-gradient(135deg,#1d4ed8,#7c3aed)", borderRadius:16, padding:"18px 16px", display:"flex", flexDirection:"column", alignItems:"center", gap:7, border:"1px solid #7c3aed" },
  winnerBtn:  { background:"rgba(255,255,255,0.15)", border:"1px solid rgba(255,255,255,0.3)", color:"#fff", borderRadius:10, padding:"8px 14px", fontWeight:700, fontSize:13, cursor:"pointer" },
  cameraBox:  { background:"#000", borderRadius:14, overflow:"hidden", aspectRatio:"16/9", position:"relative", border:"2px solid #1e3a5f" },
  cameraLabel:{ position:"absolute", top:10, left:12, fontSize:10, fontWeight:700, color:"#475569", letterSpacing:1, zIndex:2 },
  cameraFake: { width:"100%", height:"100%", background:"radial-gradient(ellipse at center,#0d1f35 0%,#000 100%)", display:"flex", alignItems:"flex-end", justifyContent:"flex-end", padding:10 },
  recDot:     { width:7, height:7, borderRadius:"50%", background:"#ef4444", marginRight:4 },
  recText:    { fontSize:11, color:"#ef4444", fontWeight:700 },
  setsRow:    { display:"flex", alignItems:"center", background:"#061120", borderRadius:14, overflow:"hidden", border:"1px solid #1e3a5f" },
  setsTeamBlock:{ flex:1, padding:"10px 8px", display:"flex", flexDirection:"column", alignItems:"center", gap:5 },
  setsTeamName: { fontSize:10, color:"#475569", fontWeight:700, textAlign:"center", lineHeight:1.2 },
  setsCount:  { fontSize:11, fontWeight:800, color:"#64748b" },
  scoreSection:{ display:"flex", alignItems:"center", background:"#061120", borderRadius:16, overflow:"hidden", border:"1px solid #1e3a5f" },
  scoreTeam:  { flex:1, padding:"12px 8px", transition:"background 0.3s", display:"flex", flexDirection:"column", alignItems:"center", gap:5 },
  teamNameScore:{ display:"flex", gap:3, flexWrap:"wrap", justifyContent:"center" },
  playerPillA:{ background:"#f59e0b18", color:"#f59e0b", borderRadius:20, padding:"2px 7px", fontSize:10, fontWeight:700 },
  playerPillB:{ background:"#10b98118", color:"#10b981", borderRadius:20, padding:"2px 7px", fontSize:10, fontWeight:700 },
  scoreNum:   { fontSize:56, fontWeight:900, lineHeight:1, letterSpacing:"-2px" },
  scoreControls:{ display:"flex", gap:5 },
  ptBtn:      { border:"none", borderRadius:8, padding:"7px 12px", fontWeight:800, fontSize:15, cursor:"pointer" },
  progressRow:{ display:"flex", justifyContent:"space-between", alignItems:"center", padding:"6px 10px", background:"#061120", borderRadius:10, border:"1px solid #1e3a5f" },
  benchBar:   { display:"flex", alignItems:"center", gap:7, flexWrap:"wrap", background:"#0a192e", borderRadius:10, padding:"7px 10px", border:"1px solid #1e3a5f" },
  benchBarLabel:{ fontSize:11, color:"#475569", fontWeight:700 },
  benchPill:  { display:"inline-flex", alignItems:"center", background:"#122236", borderRadius:20, padding:"3px 9px", fontSize:11, fontWeight:600, color:"#94a3b8" },
  replayBtn:  { flex:1, border:"none", borderRadius:12, padding:"13px", color:"#fff", fontWeight:800, fontSize:14, cursor:"pointer", transition:"background 0.3s" },
  setHistoryBox:{ background:"#061120", borderRadius:12, padding:"10px 14px", border:"1px solid #1e3a5f" },
  setHistoryTitle:{ fontSize:10, fontWeight:800, color:"#475569", letterSpacing:1, textTransform:"uppercase", marginBottom:6 },
  setHistoryRow:{ display:"flex", justifyContent:"space-between", alignItems:"center", padding:"4px 0", borderBottom:"1px solid #0a1628" },
  replayCard: { background:"#0a192e", borderRadius:14, padding:14, border:"1px solid #1e3a5f", display:"flex", flexDirection:"column", gap:7 },
  rotCard:    { background:"#061120", borderRadius:14, padding:"12px 14px", border:"1px solid #1e3a5f", display:"flex", flexDirection:"column", gap:6 },
  rotCardTitle:{ fontSize:11, fontWeight:800, color:"#475569", letterSpacing:1, textTransform:"uppercase", marginBottom:4 },
  rankCard:   { background:"#061120", borderRadius:14, padding:"14px", border:"1px solid #1e3a5f", display:"flex", flexDirection:"column", gap:8 },
  rankCardTitle:{ fontSize:11, fontWeight:800, color:"#64748b", letterSpacing:1, textTransform:"uppercase", marginBottom:4 },
  rankEmpty:  { color:"#334155", fontSize:13, textAlign:"center", padding:"12px 0" },
  rankRow:    { display:"flex", alignItems:"center", gap:8, padding:"4px 0" },
  barWrap:    { width:55, height:6, background:"#122236", borderRadius:3, overflow:"hidden", flexShrink:0 },
  barFill:    { height:"100%", borderRadius:3, transition:"width 0.5s ease" },
  resetBtn:   { background:"#122236", border:"1px solid #1e3a5f", color:"#64748b", borderRadius:8, padding:"6px 12px", fontWeight:700, fontSize:12, cursor:"pointer" },
};
